export const GET_FEED_REQUESTING = 'GET_FEED_REQUESTING';
export const GET_FEED_SUCCESSFUL = 'GET_FEED_SUCCESSFUL';
export const GET_FEED_ERROR = 'GET_FEED_ERROR';

export const ADD_PHOTO = 'ADD_PHOTO';

export const CLOSE_MODAL = 'CLOSE_MODAL';

export const CURRENT_PHOTO = 'CURRENT_PHOTO';
export const NEXT_PHOTO = 'NEXT_PHOTO';
export const PREVIOUS_PHOTO = 'PREVIOUS_PHOTO';