export const GET_FEED_REQUESTING = 'GET_FEED_REQUESTING';
export const GET_FEED_SUCCESSFUL = 'GET_FEED_SUCCESSFUL';
export const GET_FEED_ERROR = 'GET_FEED_ERROR';
export const ADD_PHOTO = 'ADD_PHOTO';