export const SET_PHOTO = 'SET_PHOTO';

export const GET_PHOTO_INFO_API_REQUESTING = 'GET_PHOTO_INFO_API_REQUESTING';
export const GET_PHOTO_INFO_API_SUCCESSFUL = 'GET_PHOTO_INFO_API_SUCCESSFUL';
export const GET_PHOTO_INFO_API_ERROR = 'GET_PHOTO_INFO_API_ERROR';

export const GET_LIKES_API_REQUESTING = 'GET_LIKES_API_REQUESTING';
export const GET_LIKES_API_SUCCESSFUL = 'GET_LIKES_API_SUCCESSFUL';
export const GET_LIKES_API_ERROR = 'GET_LIKES_API_ERROR';

export const POST_COMMENT_API_REQUESTING = 'POST_COMMENT_API_REQUESTING';
export const POST_COMMENT_API_SUCCESSFUL = 'POST_COMMENT_API_SUCCESSFUL';
export const POST_COMMENT_API_ERROR = 'POST_COMMENT_API_ERROR';

export const POST_LIKE_API_REQUESTING = 'POST_LIKE_API_REQUESTING';
export const POST_LIKE_API_SUCCESSFUL = 'POST_LIKE_API_SUCCESSFUL';
export const POST_LIKE_API_ERROR = 'POST_LIKE_API_ERROR';

export const POST_UNLIKE_API_REQUESTING = 'POST_UNLIKE_API_REQUESTING';
export const POST_UNLIKE_API_SUCCESSFUL = 'POST_UNLIKE_API_SUCCESSFUL';
export const POST_UNLIKE_API_ERROR = 'POST_UNLIKE_API_ERROR';


export const CLOSE_LIKES_MODAL = 'CLOSE_LIKES_MODAL';