export const SET_PHOTO = 'SET_PHOTO';

export const GET_PHOTO_INFO_API_REQUESTING = 'GET_PHOTO_INFO_API_REQUESTING';
export const GET_PHOTO_INFO_API_SUCCESSFUL = 'GET_PHOTO_INFO_API_SUCCESSFUL';
export const GET_PHOTO_INFO_API_ERROR = 'GET_PHOTO_INFO_API_ERROR';